# Generated by Django 3.1.2 on 2020-11-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_data',
            fields=[
                ('id', models.CharField(max_length=100000, primary_key=True, serialize=False)),
                ('publishtime', models.DateTimeField(default='')),
                ('title', models.TextField(default='')),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=False)),
                ('thumbnail', models.CharField(default='', max_length=10000)),
                ('url', models.CharField(default='', max_length=100000)),
            ],
        ),
    ]
