# Generated by Django 3.1.2 on 2020-11-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetching_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video_data',
            options={'ordering': ['publishtime']},
        ),
    ]
